classdef generation_outage
    % generator_outage - A class to store outage data
    %
    % outage = generation_outage(start_hour, duration, bus, real_power)
    % start_hour = integer input for the start hour of the year for the outage
    % duration   = integer input for the duration out the outage in hours
    % bus        = integer input for the bus location of the generator bus to be taken out during the outage
    % real_power = integer input for the real power (P) generated by the generator to be taken out during the outage.
    %
    % this.start_hour => Returns integer value for the start hour of the year for the outage
    % this.end_hour   => Returns integer value for the end out of the year for the outage
    % this.bus        => Returns integer value for the bus location for the outage
    % this.real_power => Returns integer value for the real power generated at the bus location.

    properties
        start_hour = 0
        end_hour = 0
        bus = 0
        real_power = 0
    end

    methods
        function this = generation_outage(start_hour, duration, bus, real_power)
            this.start_hour = start_hour;
            this.end_hour = duration + start_hour;
            this.bus = bus;
            this.real_power = real_power;
        end
    end
end